name: Build and Lint

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - main
  workflow_call:
  workflow_dispatch:

env:
  ENVIRONMENT_URL: ${{ vars.ENVIRONMENT_URL }}
  NEXTAUTH_SECRET: ${{ vars.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
  NEXTAUTH_URL_INTERNAL: ${{ vars.NEXTAUTH_URL_INTERNAL }}
  POSTGRES_PRISMA_URL: ${{ vars.POSTGRES_PRISMA_URL }}
  POSTGRES_URL: ${{ vars.POSTGRES_URL }}
  POSTGRES_URL_NON_POOLING: ${{ vars.POSTGRES_URL_NON_POOLING }}
  POSTGRES_URL_NO_SSL: ${{ vars.POSTGRES_URL_NO_SSL }}
  VERCEL_URL: ${{ vars.VERCEL_URL }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Jest tests
        run: npm run test
